### ISSUE TITLE
Sample of usage in Service Fabric service

### ISSUE THREAD

**Issue by mikanyg** [keithbo/Castle.Facilities.ServiceFabricIntegration#1]
The documentation (README) for this package lacks a sample of how the windsor facility is used inside a Service Fabric service.

I am left with several questions unanwsered after reading the current README.

What default SF code does the facility replace? 
What is the purpose of adding more modules?
How is a SF service boostrapped?

I think a simple sample of showing usage af both libraries would be extremely helpfull.

**Comment by keithbo** [comment]
Little late to respond to this, but I have since added Markdown detailing the usage and some code examples.
I have also added a simple test harness application that launches into a cluster and show a working example of the Windsor integration.
