### ISSUE TITLE
Update to current SF 2.6.210 (current)

### ISSUE THREAD

**Issue by bowczarek** [keithbo/Castle.Facilities.ServiceFabricIntegration#2]
Hi there, I'm about to start a project that utilizes SF but i don't like the sort of dependency injection SF Api provides, would rather use windsor with your simple integration support. Having said that, can I expect any SF maintenance update to the most recent version anytime soon ? and do you have to lock the nugetpackage to the specific version (minor)?

**Comment by mclausen** [comment]
Hi Keithbo,
We are also eagerly awaiting an update to this package, so we can continue using Windsor as DI Container together with Service Fabric.

**Comment by keithbo** [comment]
Currently the package is updated to the latest minor release of SF, 2.6.220. There is a beta 2.7 of SF on NuGet and I will update to that once it is finalized and released.
As to the original question about not locking to a specific version, SF's release pattern hasn't been very helpful in gauging constructor changes and as such I felt it best to stick to the same strategy SF does and hard-lock version numbers. I am not against opening up patch versions in the future but for now locking latest is working.
