### ISSUE TITLE
Is creating container in main method a good idea?

### ISSUE THREAD

**Issue by CDargis** [keithbo/Castle.Facilities.ServiceFabricIntegration#6]
Hi,

This is more of a question than an issue. I'm looking at adding dependency injection to a service fabric application. I've noticed a popular pattern is to create the containers in the main method before the call to Thread.Sleep():

```
private static void Main()
{
	try
	{
              using (IWindsorContainer container = new WindsorContainer())
              {
	           container.Install(new ServiceInstaller());
                   Thread.Sleep(Timeout.Infinite);
               }
        }
        ...
```
Is this a good idea? It is my understanding that the Main() method executes once when the process first starts while the service fabric runtime creates/destroys services. When is the `Dispose()` method on the container called? How is the lifetime of the container properly managed in this case?  What about the lifetime of the objects within the container?

**Comment by CDargis** [comment]
If the service is shut down, does the object get released from the container?

**Comment by keithbo** [comment]
@CDargis Generally speaking you want to have your injection container, Windsor in this case, to exist as close to the initialization of your application as possible. The less you need to manually control the better, especially as you are intending to leveraging the primary strength of the container, lifecycle management.
For a long-lived service such as Service Fabric the complexity is that the Main() entry point is really just a bootstrap of sorts, but it needs to keep running to prevent the background threads from being terminated. It registers the service types you intend to use with the Runtime and then thread sleeps until the node ends the process.
```
    try
    {
        ServiceRuntime.RegisterServiceAsync("Stateful1Type", context => new Stateful1(context)).GetAwaiter().GetResult();

        ServiceEventSource.Current.ServiceTypeRegistered(Process.GetCurrentProcess().Id, typeof(Stateful1).Name);

        // Prevents this host process from terminating so services keep running.
        Thread.Sleep(Timeout.Infinite);
    }
```
With Windsor this actually works pretty well as the trigger to tear down the container, notice the `using(...)`, and dispose of any lifecycle managed registrations. The assumption is that if we got to this point either the service shutdown gracefully or it died horribly and we are going down anyway.
WIth ServiceFabricIntegration the container uses its own factory delegate for `RegisterServiceAsync(...)`, you can use whatever lifecycle you wish but Service Fabric will only instantiate one service per registration anyways so Singleton makes the most sense for services. Actors are a little different and have their own lifetime management in Service Fabric that I've harnessed to trigger container disposal.
Kind of as an aside, Service Fabric doesn't really have a "shut down" for services. The runtime does its best effort to make sure they get to a safe point to be terminated (ie, RunAsync(), OnChangeRole, OnClose, OnDataLoss, etc).

Hope that helps some.

**Comment by CDargis** [comment]
Thanks @keithbo
