### ISSUE TITLE
ILogger

### ISSUE THREAD

**Issue by koderi-dp** [keithbo/Castle.Facilities.ServiceFabricIntegration#7]
Hi,

if i create installer, like

`  public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.AddFacility<TypedFactoryFacility>();
            container.AddFacility<ServiceFabricFacility>();
            container.Register(Component.For<GatewayService>().AsStatelessService("Gateway"));
}
`
i want to register ilogger Microsoft.Extensions.Logging as component, but ilogger factory for service fabrics is receiving in constructor ServiceContext, how to get service context from ServiceFabricFacility?

**Comment by keithbo** [comment]
Hi @danijel-peric 

If I understand your issue correctly, you want to do something like:

`container.Register(Component.For<ILoggerFactory>().ImplementedBy<LoggerFactory>())`

then a stateless service with constructor:

`public GatewayService(StatelessServiceContext serviceContext, ILoggerFactory loggerFactory) { ... }`

But then I don't understand where your ServiceContext issue comes in.

The underlying ServiceFabric runtime is where StatelessServiceContext is constructed (internal constructors), it is not stored as a component in the Windsor Container. As such you can't inject, or create, it as a dependency anywhere else via Windsor.

**Comment by keithbo** [comment]
Closing this out as there doesn't seem to be any further response.
